version: '3.3'
services:
    borgbackup-docker-alpine:
        container_name: youruniquename
        hostname: youruniquename
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'youruniquename_dbtemp:/backup/mariadb'
            - '/backupsource1:/backup/backuptarget1'
            - '/backupsource2:/backup/backuptarget2'
            - '/backupsource3:/backup/backuptarget3'
            - '/opt/backup/secrets/known_hosts:/root/.ssh/known_hosts'
            - '/opt/backup/secrets/id_rsa:/root/.ssh/id_rsa'
            - '/opt/backup/secrets/borg_repo_pw:/root/borg_repo_pw'
        environment:
            - 'BORG_REPO=ssh://u231445-sub1@u231445.your-storagebox.de:23/./test'
            - 'BORG_RSH=ssh -i /root/.ssh/id_rsa'
            - BORG_PASSPHRASE=/root/borg_repo_pw
            - BACKUP_INTERVAL=5min
            - MARIADB_CONTAINER=mariadb_test
            - MARIADB_USER=root
            - MARIADB_PW=secretadmin
        image: 'shiz0/borgbackup-docker-alpine:latest'

volumes:
  borgbackup_test_dbtemp:
