version: '3.3'
services:
    borgbackup-docker-alpine:
        container_name: <youruniquename>
        hostname: <youruniquename>
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - <youruniquename>_dbtemp:/backup/mariadb
            - /backupsource1:/backup/backuptarget1
            - /backupsource2:/backup/backuptarget2
            - /backupsource3:/backup/backuptarget3
            - /opt/backup/secrets/known_hosts:/root/.ssh/known_hosts
            - /opt/backup/secrets/id_rsa:/root/.ssh/id_rsa
            - /opt/backup/secrets/borg_repo_pw:/root/borg_repo_pw
            - /opt/backup/secrets/mariadb_pw:/root/mariadb_pw             # Optional, see Readme
        environment:
            - BORG_REPO=ssh://host:port/./<reponame>
            - BORG_RSH=ssh -i /root/.ssh/id_rsa
            - BORG_PASSPHRASE=/root/borg_repo_pw
            - BACKUP_INTERVAL=5min
            - MARIADB_CONTAINER=mariadb_test
            - MARIADB_USER=root
            - MARIADB_PW=secretadmin
            - BORG_INIT_CMD=--encryption=repokey
            - BORG_CREATE_CMD=--stats ::{now:%Y-%m-%d_%H-%M-%S} /backup
            - BORG_PRUNE_CMD=-n --list --force --keep-last 5
        image: 'shiz0/borgbackup-docker-alpine:latest

volumes:
  youruniquename_dbtemp:
